### ISSUE TITLE
Typo in Readme file (Calman's bit depth)

### ISSUE THREAD

**Issue by MisterTickle** [ledoge/dogegen#8]
I think this is wrong:
"With ColourSpace, 8 and 10 bit patterns can be used (higher bit depths are not supported by Windows), while Calman's interface only supports 10 bit patterns."

Calman only supports 8 bit, it has no support for 10 bit.

**Comment by ledoge** [comment]
The wording could be better, but this specifically refers to the fact that the TPG interface as implemented by Calman only supports 10 bit values, i.e. the values received by dogegen will always be 10 bit.

**Comment by ledoge** [comment]
I've updated the readme to reword that part, please let me know if you find it more clear now.

**Comment by MisterTickle** [comment]
That's better IMHO yes. Many thanks! :)
